import { redirect, notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import Link from 'next/link'
import { ArrowLeft, CircleCheck, CircleAlert, CircleDashed, FileText, Loader2 } from 'lucide-react'
import { FaceVerification } from '@/components/face-verification'
import { ScreeningLiveRefresh } from '@/components/screening-live-refresh'

export default async function ScreeningPage({params}:{params:Promise<{id:string}>}) {
 const {id}=await params; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/auth/login')
 const {data:s}=await supabase.from('screenings').select('*').eq('id',id).single(); if(!s || s.user_id!==user.id) notFound()
 const {data:checks}=await supabase.from('screening_checks').select('*').eq('screening_id',id).order('created_at'); const {data:findings}=await supabase.from('screening_findings').select('*').eq('screening_id',id).order('created_at')
 const processing=s.status==='processing'||s.status==='created'
 return <main className="min-h-screen p-4 md:p-8"><ScreeningLiveRefresh status={s.status}/><div className="mx-auto max-w-5xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={16}/>Dashboard</Link><div className="material mt-5 rounded-[30px] p-6 md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><p className="text-sm text-white/40">Screening</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.04em]">{s.document_type||'Document screening'}</h1><p className="mt-2 text-sm text-white/40">{new Date(s.created_at).toLocaleString()}</p></div><Assessment value={s.overall_assessment} processing={processing}/></div>{processing&&<div className="mt-6 rounded-2xl bg-white/[.045] p-4"><div className="flex items-center gap-3"><Loader2 size={18} className="animate-spin text-white/60"/><div><p className="text-sm font-medium">Analysis in progress</p><p className="mt-1 text-xs text-white/35">OCR, document validation and forensic checks are running. This page updates automatically.</p></div></div></div>}<div className="mt-6 flex justify-end"><Link href={`/screenings/${id}/report`} className="pressable inline-flex items-center gap-2 rounded-xl bg-white/[.08] px-4 py-2.5 text-sm text-white/75"><FileText size={16}/>View report</Link></div><div className="mt-8 grid gap-4 md:grid-cols-2"><section className="material-soft rounded-2xl p-5"><h2 className="font-medium">Verification checks</h2><div className="mt-4 space-y-2">{checks?.length?checks.map(c=><div key={c.id} className="flex items-center justify-between rounded-xl bg-white/[.035] px-3 py-3"><span className="text-sm capitalize text-white/65">{c.check_type.replaceAll('_',' ')}</span><Status status={c.status}/></div>):<p className="py-8 text-sm text-white/35">{processing?'Checks will appear as analysis completes.':'No results were generated.'}</p>}</div></section><section className="material-soft rounded-2xl p-5"><h2 className="font-medium">Findings</h2><div className="mt-4 space-y-3">{findings?.length?findings.map(f=><div key={f.id} className="rounded-xl bg-white/[.035] p-3"><div className="flex items-center gap-2"><CircleAlert size={15} className="text-white/45"/><span className="text-sm font-medium">{f.title}</span></div><p className="mt-1 text-sm leading-6 text-white/45">{f.description}</p></div>):<p className="py-8 text-sm text-white/35">{processing?'Findings will appear after the checks complete.':'No findings.'}</p>}</div></section></div>{!processing&&<FaceVerification screeningId={id}/>}</div></div></main>
}
function Assessment({value,processing}:{value:string|null,processing:boolean}){return <div className="rounded-2xl bg-white/[.06] px-4 py-3 text-sm capitalize text-white/70">{processing?'processing':value?.replaceAll('_',' ')||'not evaluated'}</div>}
function Status({status}:{status:string}){const Icon=status==='passed'?CircleCheck:status==='not_evaluated'?CircleDashed:CircleAlert;return <span className="flex items-center gap-2 text-xs capitalize text-white/45"><Icon size={15}/>{status.replaceAll('_',' ')}</span>}
