'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { UploadCloud, FileText, ArrowLeft, Loader2 } from 'lucide-react'
import Link from 'next/link'

const SCREENING_API = 'https://sih26188-ai-identity-screening.onrender.com'

export default function NewScreening(){
 const router=useRouter(); const supabase=createClient(); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 async function submit(){ if(!file)return; setBusy(true);setError(''); const {data:{user}}=await supabase.auth.getUser(); if(!user){router.push('/auth/login');return}
 const {data:screening,error:e}=await supabase.from('screenings').insert({user_id:user.id,status:'created'}).select('id').single(); if(e||!screening){setError(e?.message||'Unable to create screening.');setBusy(false);return}
 const path=`${user.id}/${screening.id}/${crypto.randomUUID()}-${file.name}`; const {error:up}=await supabase.storage.from('screening-documents').upload(path,file,{contentType:file.type,upsert:false}); if(up){await supabase.from('screenings').delete().eq('id',screening.id);setError(up.message);setBusy(false);return}
 const {error:row}=await supabase.from('screening_documents').insert({screening_id:screening.id,user_id:user.id,storage_path:path,original_filename:file.name,mime_type:file.type,file_size_bytes:file.size}); if(row){setError(row.message);setBusy(false);return} const {data:{session}}=await supabase.auth.getSession(); const response=await fetch(`${SCREENING_API}/v1/screenings/${screening.id}/analyze`,{method:'POST',headers:{Authorization:`Bearer ${session?.access_token||''}`}}); if(!response.ok){const body=await response.json().catch(()=>({}));setError(body.detail||'Analysis could not be started.');setBusy(false);return} router.push(`/screenings/${screening.id}`)
 }
 return <main className="min-h-screen p-4 md:p-8"><div className="mx-auto max-w-3xl"><Link href="/dashboard" className="focus-ring inline-flex items-center gap-2 text-sm text-white/50 hover:text-white"><ArrowLeft size={16}/>Back</Link><div className="material mt-5 rounded-[30px] p-6 md:p-10"><p className="text-sm text-white/40">New screening</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.04em]">Start with the document.</h1><p className="mt-2 max-w-xl text-white/50">Upload an identity document. The next processing stage will run actual OCR, validation and forensic checks.</p><label className="pressable mt-8 block cursor-pointer rounded-[26px] border border-dashed border-white/15 bg-white/[.025] p-8 text-center hover:bg-white/[.045] md:p-14"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="sr-only" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-white/[.07]"><UploadCloud size={24} className="text-white/70"/></div><div className="mt-5 font-medium">{file?file.name:'Choose a document'}</div><div className="mt-1 text-sm text-white/35">JPG, PNG, WEBP or PDF</div></label>{file&&<div className="mt-4 flex items-center gap-3 rounded-2xl bg-white/[.045] p-4"><FileText size={20} className="text-white/55"/><div className="min-w-0 flex-1"><div className="truncate text-sm">{file.name}</div><div className="text-xs text-white/35">{(file.size/1024/1024).toFixed(2)} MB</div></div></div>}{error&&<p className="mt-4 rounded-xl bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={!file||busy} onClick={submit} className="pressable focus-ring mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3.5 font-medium text-black disabled:cursor-not-allowed disabled:opacity-40">{busy?<><Loader2 size={18} className="animate-spin"/>Uploading and analyzing…</>:'Create screening'}</button><p className="mt-4 text-center text-xs leading-5 text-white/30">No verification result is generated at upload time. Analysis will only be reported after the corresponding real checks run.</p></div></div></main>
}
