'use client'
import { useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { UploadCloud, FileText, ArrowLeft, Loader2 } from 'lucide-react'
import Link from 'next/link'

const SCREENING_API = 'https://sih26188-ai-identity-screening.onrender.com'

export default function NewScreening(){
 const router=useRouter(); const supabase=createClient(); const inputRef=useRef<HTMLInputElement>(null); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [drag,setDrag]=useState(false); const [error,setError]=useState('')
 function choose(f?:File){ if(!f)return; const ok=['application/pdf','image/jpeg','image/png','image/webp'].includes(f.type); if(!ok){setError('Please upload a PDF, JPG, PNG or WEBP file.');return} setError('');setFile(f) }
 async function submit(){ if(!file)return; setBusy(true);setError(''); const {data:{user}}=await supabase.auth.getUser(); if(!user){router.push('/auth/login');return}
 const {data:screening,error:e}=await supabase.from('screenings').insert({user_id:user.id,status:'created'}).select('id').single(); if(e||!screening){setError(e?.message||'Unable to create screening.');setBusy(false);return}
 const path=`${user.id}/${screening.id}/${crypto.randomUUID()}-${file.name}`; const {error:up}=await supabase.storage.from('screening-documents').upload(path,file,{contentType:file.type,upsert:false}); if(up){await supabase.from('screenings').delete().eq('id',screening.id);setError(up.message);setBusy(false);return}
 const {error:row}=await supabase.from('screening_documents').insert({screening_id:screening.id,user_id:user.id,storage_path:path,original_filename:file.name,mime_type:file.type,file_size_bytes:file.size}); if(row){setError(row.message);setBusy(false);return} const {data:{session}}=await supabase.auth.getSession(); const response=await fetch(`${SCREENING_API}/v1/screenings/${screening.id}/analyze`,{method:'POST',headers:{Authorization:`Bearer ${session?.access_token||''}`}}); if(!response.ok){const body=await response.json().catch(()=>({}));setError(body.detail||'Analysis could not be started.');setBusy(false);return} router.push(`/screenings/${screening.id}`)
 }
 return <main className="min-h-screen bg-white p-4 text-neutral-900 md:p-8"><div className="mx-auto max-w-2xl"><Link href="/dashboard" className="focus-ring inline-flex items-center gap-2 text-sm text-neutral-500 hover:text-black"><ArrowLeft size={16}/>Back</Link><div className="mt-8"><p className="text-sm font-medium text-neutral-500">Document screening</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.04em]">Upload a document</h1><p className="mt-2 text-neutral-500">Drop a document here. We’ll start the checks in the background.</p><div onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files?.[0])}} onClick={()=>!busy&&inputRef.current?.click()} className={`pressable mt-8 cursor-pointer rounded-3xl border-2 border-dashed p-10 text-center md:p-16 ${drag?'border-black bg-neutral-50':'border-neutral-200 hover:border-neutral-400 hover:bg-neutral-50'}`}><input ref={inputRef} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>choose(e.target.files?.[0])}/><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-neutral-100"><UploadCloud size={25}/></div><div className="mt-5 text-lg font-medium">{file?file.name:'Drag & drop your document'}</div><div className="mt-1 text-sm text-neutral-400">or click to browse · PDF, JPG, PNG, WEBP</div></div>{file&&<div className="mt-4 flex items-center gap-3 rounded-2xl border border-neutral-200 bg-neutral-50 p-4"><FileText size={20} className="text-neutral-500"/><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{file.name}</div><div className="text-xs text-neutral-400">{(file.size/1024/1024).toFixed(2)} MB</div></div></div>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}<button disabled={!file||busy} onClick={e=>{e.stopPropagation();submit()}} className="pressable focus-ring mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-black px-5 py-3.5 font-medium text-white disabled:cursor-not-allowed disabled:opacity-30">{busy?<><Loader2 size={18} className="animate-spin"/>Uploading…</>:'Screen document'}</button><p className="mt-4 text-center text-xs text-neutral-400">The upload returns immediately; AI analysis continues in the background.</p></div></div></main>
}
