import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { Sidebar } from '@/components/sidebar'
import Link from 'next/link'
import { ArrowUpRight, FileCheck2, ShieldAlert, Clock3 } from 'lucide-react'

export default async function Dashboard(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/auth/login')
 const {data:screenings}=await supabase.from('screenings').select('id,status,document_type,overall_assessment,created_at').order('created_at',{ascending:false}).limit(6)
 return <main className="mx-auto flex min-h-screen max-w-[1500px] gap-4 p-4 md:p-6"><Sidebar/><section className="min-w-0 flex-1"><header className="material rounded-[28px] px-6 py-5 md:px-8"><p className="text-sm text-white/45">Screening workspace</p><div className="mt-1 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-3xl font-semibold tracking-[-.04em] md:text-4xl">Overview</h1><p className="mt-2 text-white/50">Analyze identity documents using real verification checks.</p></div><Link href="/screenings/new" className="pressable focus-ring inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-medium text-black">New screening <ArrowUpRight size={17}/></Link></div></header><div className="mt-4 grid gap-4 sm:grid-cols-3"><Stat icon={<FileCheck2 size={18}/>} label="Screenings" value={String(screenings?.length ?? 0)}/><Stat icon={<ShieldAlert size={18}/>} label="High risk" value={String(screenings?.filter(s=>s.overall_assessment==='high_risk').length ?? 0)}/><Stat icon={<Clock3 size={18}/>} label="In progress" value={String(screenings?.filter(s=>s.status==='processing').length ?? 0)}/></div><section className="material mt-4 rounded-[28px] p-5 md:p-7"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Recent screenings</h2><p className="text-sm text-white/40">Only actual records from your account appear here.</p></div><Link href="/screenings" className="text-sm text-white/55 hover:text-white">View all</Link></div>{!screenings?.length?<div className="py-20 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[.06]"><FileCheck2 size={20} className="text-white/45"/></div><p className="mt-4 font-medium">No screenings yet.</p><p className="mt-1 text-sm text-white/40">Start with a document when you're ready.</p></div>:<div className="mt-5 divide-y divide-white/[.06]">{screenings.map(s=><Link href={`/screenings/${s.id}`} key={s.id} className="pressable flex items-center justify-between gap-4 py-4"><div><div className="font-medium">{s.document_type||'Document pending analysis'}</div><div className="mt-1 text-xs text-white/35">{new Date(s.created_at).toLocaleString()}</div></div><div className="text-right"><div className="text-sm text-white/65">{s.overall_assessment?.replaceAll('_',' ')||s.status}</div><ArrowUpRight size={15} className="ml-auto mt-1 text-white/25"/></div></Link>)}</div>}</section></section></main>
}
function Stat({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="material rounded-[24px] p-5"><div className="flex items-center gap-2 text-sm text-white/45">{icon}{label}</div><div className="mt-3 text-3xl font-semibold tracking-[-.04em]">{value}</div></div>}
