import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { Sidebar } from '@/components/sidebar'
import { DeleteScreeningButton } from '@/components/delete-screening-button'
import Link from 'next/link'
import { ArrowUpRight, FileCheck2, ShieldAlert, Clock3, ScanLine } from 'lucide-react'

export default async function Dashboard(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/auth/login')
 const {data:screenings}=await supabase.from('screenings').select('id,status,document_type,overall_assessment,created_at').order('created_at',{ascending:false}).limit(20)
 return <main className="mx-auto flex min-h-screen max-w-[1200px] gap-4 bg-white p-4 text-neutral-900 md:p-6"><Sidebar/><section className="min-w-0 flex-1"><header className="rounded-3xl border border-neutral-200 bg-white px-5 py-6 shadow-sm md:px-8"><p className="text-sm font-medium text-neutral-500">AI-assisted document screening</p><div className="mt-1 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-3xl font-semibold tracking-[-.04em] md:text-4xl">Screen a document</h1><p className="mt-2 text-neutral-500">Fast OCR, validation, forensic checks and risk assessment.</p></div><Link href="/screenings/new" className="pressable focus-ring inline-flex items-center justify-center gap-2 rounded-2xl bg-black px-6 py-3.5 text-sm font-medium text-white"><ScanLine size={18}/> Scan document</Link></div></header><div className="mt-4 grid gap-3 sm:grid-cols-3"><Stat icon={<FileCheck2 size={18}/>} label="Screenings" value={String(screenings?.length ?? 0)}/><Stat icon={<ShieldAlert size={18}/>} label="High risk" value={String(screenings?.filter(s=>s.overall_assessment==='high_risk').length ?? 0)}/><Stat icon={<Clock3 size={18}/>} label="In progress" value={String(screenings?.filter(s=>s.status==='processing').length ?? 0)}/></div><section className="mt-4 rounded-3xl border border-neutral-200 bg-white p-5 shadow-sm md:p-7"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Previous screenings</h2><p className="text-sm text-neutral-500">Delete old records and their uploaded files anytime.</p></div><Link href="/screenings/new" className="text-sm font-medium text-neutral-700 hover:text-black">Scan again</Link></div>{!screenings?.length?<div className="py-20 text-center"><p className="font-medium">No screenings yet.</p><p className="mt-1 text-sm text-neutral-400">Tap Scan document to begin.</p></div>:<div className="mt-5 divide-y divide-neutral-100">{screenings.map(s=><div key={s.id} className="flex items-center gap-3 py-4"><Link href={`/screenings/${s.id}`} className="pressable min-w-0 flex-1"><div className="font-medium">{s.document_type||'Document pending analysis'}</div><div className="mt-1 text-xs text-neutral-400">{new Date(s.created_at).toLocaleString()}</div></Link><div className="text-right"><div className="text-sm capitalize text-neutral-600">{s.overall_assessment?.replaceAll('_',' ')||s.status}</div></div><DeleteScreeningButton screeningId={s.id}/></div>)}</div>}</section></section></main>
}
function Stat({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-sm text-neutral-500">{icon}{label}</div><div className="mt-2 text-2xl font-semibold tracking-[-.04em]">{value}</div></div>}
